# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"num_tries_gt_zero": "warp_loss.ipynb",
         "warp_loss": "warp_loss.ipynb"}

modules = ["losses.py"]

doc_url = "https://NegatioN.github.io/WARP-Pytorch/"

git_url = "https://github.com/NegatioN/WARP-Pytorch/tree/master/"

def custom_doc_links(name): return None
